[build]
  command = "echo 'No build needed'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"   # Use a modern Node version

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 301

[[redirects]]
  from = "/discord"
  to = "/.netlify/functions/invite?redirect=true"
  status = 301

[[redirects]]
  from = "/api/members"
  to = "/api/users"
  status = 301

[[redirects]]
  from = "/api/member-count"
  to = "/api/user-count"
  status = 301
